import { InterestItem } from "../types/mypage/profileType";

export const interestItems: InterestItem[] = [
  { id: 1, title: "🎤 KPOP" },
  { id: 2, title: "💪 운동" },
  { id: 3, title: "📚 언어교환" },
  { id: 4, title: "🍔 맛집" },
  { id: 5, title: "📺 드라마" },
  { id: 6, title: "🥐 베이킹" },
  { id: 7, title: "🎬 넷플릭스" },
  { id: 8, title: "🎞️ 유튜브" },
  { id: 9, title: "🍳 요리" },
  { id: 10, title: "🎊 파티" },
  { id: 11, title: "🎵 노래" },
  { id: 12, title: "📸 사진" },
  { id: 13, title: "📝 블로그" },
  { id: 14, title: "🎥 영화" },
  { id: 15, title: "⚜️ DIY" },
  { id: 16, title: "🏞️ 한강" },
  { id: 17, title: "☕️ 카페" },
  { id: 18, title: "💄 메이크업" },
  { id: 19, title: "🖌️ 드로잉" },
  { id: 20, title: "🖼️ 전시회" },
  { id: 21, title: "🧑🏻‍💻 코딩" },
  { id: 22, title: "🎮 게임" },
  { id: 23, title: "🛍️ 쇼핑" },
  { id: 24, title: "🧩 방탈출" },
  { id: 25, title: "🃏 보드게임" },
  { id: 26, title: "🐶 반려동물" },
  { id: 27, title: "✨ MBTI" },
  { id: 28, title: "🍺 수제맥주" },
  { id: 29, title: "🍷 와인" },
  { id: 30, title: "👩‍🎤 뮤지컬" },
];
